-- Migration from 194 to 195

CREATE DOMAIN PATTERN_TYPE AS VARCHAR(40) CHECK (VALUE IN ('PATTERN', 'VALUES', 'RANGES'));

ALTER TABLE IF EXISTS PROPERTY_TYPES
    ADD COLUMN PATTERN TEXT_VALUE,
    ADD COLUMN PATTERN_TYPE PATTERN_TYPE,
    ADD COLUMN PATTERN_REGEX TEXT_VALUE;

