-- Migration from 195 to 196



ALTER TABLE IF EXISTS EXPERIMENT_TYPES
 ADD COLUMN IS_MANAGED_INTERNALLY BOOLEAN_CHAR NOT NULL DEFAULT 'F';


ALTER TABLE IF EXISTS MATERIAL_TYPES
 ADD COLUMN IS_MANAGED_INTERNALLY BOOLEAN_CHAR NOT NULL DEFAULT 'F';

ALTER TABLE IF EXISTS DATA_SET_TYPES
 ADD COLUMN IS_MANAGED_INTERNALLY BOOLEAN_CHAR NOT NULL DEFAULT 'F';

ALTER TABLE IF EXISTS SAMPLE_TYPES
 ADD COLUMN IS_MANAGED_INTERNALLY BOOLEAN_CHAR NOT NULL DEFAULT 'F';


ALTER TABLE IF EXISTS EXPERIMENT_TYPES ADD CONSTRAINT ET_BK_UK UNIQUE(CODE,IS_MANAGED_INTERNALLY);
ALTER TABLE IF EXISTS MATERIAL_TYPES ADD CONSTRAINT MT_BK_UK UNIQUE(CODE,IS_MANAGED_INTERNALLY);
ALTER TABLE IF EXISTS SAMPLE_TYPES ADD CONSTRAINT ST_BK_UK UNIQUE(CODE,IS_MANAGED_INTERNALLY);
ALTER TABLE IF EXISTS DATA_SET_TYPES ADD CONSTRAINT DST_BK_UK UNIQUE(CODE,IS_MANAGED_INTERNALLY);




