-- Migration from 195 to 196



ALTER TABLE IF EXISTS EXPERIMENT_TYPES
 ADD COLUMN IS_MANAGED_INTERNALLY BOOLEAN_CHAR NOT NULL DEFAULT 'F';


ALTER TABLE IF EXISTS MATERIAL_TYPES
 ADD COLUMN IS_MANAGED_INTERNALLY BOOLEAN_CHAR NOT NULL DEFAULT 'F';

ALTER TABLE IF EXISTS DATA_SET_TYPES
 ADD COLUMN IS_MANAGED_INTERNALLY BOOLEAN_CHAR NOT NULL DEFAULT 'F';

ALTER TABLE IF EXISTS SAMPLE_TYPES
 ADD COLUMN IS_MANAGED_INTERNALLY BOOLEAN_CHAR NOT NULL DEFAULT 'F';




