-- Creating domains

CREATE DOMAIN BOOLEAN_CHAR AS BOOLEAN DEFAULT FALSE;
CREATE DOMAIN MD5_SUM AS VARCHAR(32);
CREATE DOMAIN EMAIL AS VARCHAR(50);
CREATE DOMAIN TECH_ID AS BIGINT;
CREATE DOMAIN TIME_STAMP AS TIMESTAMP;
CREATE DOMAIN USER_NAME AS VARCHAR(20);


-- Creating tables

CREATE TABLE USERS (
	ID TECH_ID NOT NULL,
	EMAIL EMAIL NOT NULL,
	USER_NAME USER_NAME,
	ENCRYPTED_PASSWORD MD5_SUM,
	IS_ADMIN BOOLEAN_CHAR NOT NULL DEFAULT 'F',
	IS_PERMANENT BOOLEAN_CHAR NOT NULL DEFAULT 'F',
	REGISTRATION_TIMESTAMP TIME_STAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	EXPIRATION_TIMESTAMP TIME_STAMP);

-- Creating primary key constraints

ALTER TABLE USERS ADD CONSTRAINT USER_PK PRIMARY KEY(ID);

-- Creating sequences

CREATE SEQUENCE USER_ID_SEQ;

