-- Creating domains

CREATE DOMAIN BOOLEAN_CHAR AS BOOLEAN DEFAULT FALSE;
CREATE DOMAIN MD5_SUM AS VARCHAR(32);
CREATE DOMAIN EMAIL AS VARCHAR(50);
CREATE DOMAIN FILE_NAME AS VARCHAR(250);
CREATE DOMAIN TECH_ID AS BIGINT;
CREATE DOMAIN TIME_STAMP AS TIMESTAMP;
CREATE DOMAIN USER_NAME AS VARCHAR(20);

-- Creating tables

CREATE TABLE FILES (
	ID TECH_ID NOT NULL,
	NAME FILE_NAME NOT NULL,
	PATH FILE_NAME NOT NULL,
	USER_ID_REGISTERER TECH_ID NOT NULL,
	REGISTRATION_TIMESTAMP TIME_STAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	EXPIRATION_TIMESTAMP TIME_STAMP NOT NULL);
    
CREATE TABLE FILE_SHARES (
	FILE_ID TECH_ID NOT NULL,
	USER_ID TECH_ID NOT NULL);

CREATE TABLE USERS (
	ID TECH_ID NOT NULL,
	EMAIL EMAIL NOT NULL,
	USER_NAME USER_NAME,
	ENCRYPTED_PASSWORD MD5_SUM,
	IS_EXTERNALLY_AUTHENTICATED BOOLEAN_CHAR NOT NULL,
	IS_ADMIN BOOLEAN_CHAR NOT NULL,
	IS_PERMANENT BOOLEAN_CHAR NOT NULL,
	REGISTRATION_TIMESTAMP TIME_STAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	EXPIRATION_TIMESTAMP TIME_STAMP);
	
-- Creating primary key constraints

ALTER TABLE FILES ADD CONSTRAINT FILES_PK PRIMARY KEY(ID);
ALTER TABLE USERS ADD CONSTRAINT USER_PK PRIMARY KEY(ID);

-- Creating unique constraints

ALTER TABLE FILES ADD CONSTRAINT FILE_BK_UK UNIQUE(PATH);
ALTER TABLE USERS ADD CONSTRAINT USER_BK_UK UNIQUE(EMAIL);

-- Creating foreign key constraints

ALTER TABLE FILES ADD CONSTRAINT FILE_USER_FK FOREIGN KEY (USER_ID_REGISTERER) REFERENCES USERS(ID);
ALTER TABLE FILE_SHARES ADD CONSTRAINT FS_FILE_FK FOREIGN KEY (FILE_ID) REFERENCES FILES(ID);
ALTER TABLE FILE_SHARES ADD CONSTRAINT FS_USER_FK FOREIGN KEY (USER_ID) REFERENCES USERS(ID);

-- Creating sequences

CREATE SEQUENCE FILE_ID_SEQ;
CREATE SEQUENCE USER_ID_SEQ;

