-- Creating domains

CREATE DOMAIN BOOLEAN_CHAR AS BOOLEAN DEFAULT FALSE;
CREATE DOMAIN MD5_SUM AS VARCHAR(32);
CREATE DOMAIN OBJECT_NAME AS VARCHAR(50);
CREATE DOMAIN TECH_ID AS BIGINT;
CREATE DOMAIN USER_ID AS VARCHAR(20);


-- Creating tables

CREATE TABLE USERS (
	ID TECH_ID NOT NULL,
	EMAIL OBJECT_NAME NOT NULL,
	USER_ID USER_ID,
	ENCRYPTED_PASSWORD MD5_SUM,
	IS_ADMIN BOOLEAN_CHAR NOT NULL DEFAULT 'F',
	IS_PERMANENT BOOLEAN_CHAR NOT NULL DEFAULT 'F');

-- Creating primary key constraints

ALTER TABLE USERS ADD CONSTRAINT USER_PK PRIMARY KEY(ID);

-- Creating sequences

CREATE SEQUENCE USER_ID_SEQ;

