-- Call trigger for insert and update

DROP TRIGGER UPDATE_QUOTA_GROUP_ID_ON_INSERT_USER ON USERS;

ALTER FUNCTION UPDATE_QUOTA_GROUP_ID_ON_INSERT_USER() RENAME TO UPDATE_QUOTA_GROUP_ID_ON_INSERT_UPDATE_USER;

CREATE TRIGGER UPDATE_QUOTA_GROUP_ID_ON_INSERT_UPDATE_USER BEFORE INSERT OR UPDATE ON USERS
    FOR EACH ROW EXECUTE PROCEDURE UPDATE_QUOTA_GROUP_ID_ON_INSERT_UPDATE_USER();
