package ch.ethz.sis.openbis.generic.server.asapi.v3;

public enum TransactionStatus
{
    NEW, BEGIN_STARTED, BEGIN_FINISHED, PREPARE_STARTED, PREPARE_FINISHED, COMMIT_STARTED, COMMIT_INCONSISTENT, COMMIT_FINISHED, ROLLBACK_STARTED, ROLLBACK_FINISHED
}
