-- Remove NOT NULL constraint from FILES.USER_ID that has been added in old version of 010 by mistake

ALTER TABLE FILES ALTER COLUMN USER_ID SET NULL;

-- Remove column USERS.IS_PERMANENT as it duplicate USERS.EXPIRATION_DATE

ALTER TABLE USERS DROP COLUMN IS_PERMANENT;

-- Switch file and user retention from hours to days

UPDATE QUOTA_GROUPS 
	SET FILE_RETENTION = FILE_RETENTION / 24, USER_RETENTION = USER_RETENTION / 24;
UPDATE QUOTA_GROUPS SET FILE_RETENTION = 1 WHERE FILE_RETENTION = 0;
UPDATE QUOTA_GROUPS SET USER_RETENTION = 1 WHERE USER_RETENTION = 0;

-- Switch domain duration (and QUOTA_GROUPS.USER_RETENTION and QUOTA_GROUP.FILE_RETENTION) 
-- from BIGINT to INTEGER

DROP DOMAIN DURATION;
CREATE DOMAIN DURATION AS INTEGER;

ALTER TABLE QUOTA_GROUPS ALTER COLUMN FILE_RETENTION DURATION;
ALTER TABLE QUOTA_GROUPS ALTER COLUMN USER_RETENTION DURATION;

-- Add FILES.REGISTRATOR_CODE and set it to the value refered to by the FILES.USER_ID

ALTER TABLE FILES ADD REGISTRATOR_CODE USER_CODE;
UPDATE FILES F SET REGISTRATOR_CODE = (SELECT USER_CODE FROM USERS U WHERE U.ID = F.USER_ID);
UPDATE FILES SET REGISTRATOR_CODE = 'UNKNOWN' WHERE REGISTRATOR_CODE IS NULL;
ALTER TABLE FILES ALTER COLUMN REGISTRATOR_CODE SET NOT NULL;